INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Aruba' ,'ABW');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Afghanistan' ,'AFG');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Angola' ,'AGO');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Albania' ,'ALB');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Andorra' ,'AND');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('United Arab Emirates' ,'ARE');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Argentina' ,'ARG');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Australia' ,'AUS');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Austria' ,'AUT');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Azerbaijan' ,'AZE');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Burundi' ,'BDI');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Belgium' ,'BEL');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Benin' ,'BEN');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Burkina Faso	' ,'BFA');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Bangladesh' ,'BGD');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Bulgaria' ,'BGR');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Bahrain' ,'BHR');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Bahamas' ,'BHS');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Bosnia and Herzegovina' ,'BIH');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Belarus' ,'BLR');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Belize' ,'BLZ');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Bermuda' ,'BMU');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Bolivia' ,'BOL');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Brazil' ,'BRA');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Barbados' ,'BRB');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Brunei Darussalam' ,'BRN');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Bhutan', 'BTN');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Botswana' ,'BWA');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Central African Republic' ,'CAF');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Canada' ,'CAN');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Switzerland' ,'CHE');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Chile' ,'CHL');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('China' ,'CHN');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Cote d Ivoire' ,'CIV');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Cameroon' ,'CMR');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('The democratic republig of Congo' ,'COD');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('The Congo' ,'COG');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Colombia' ,'COL');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Cabo Verde' ,'CPV');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Costa Rica' ,'CRI');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Cuba' ,'CUB');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Cyprus' ,'CYP');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Czechia' ,'CZE');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Germany' ,'DEU');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Djibouti' ,'DJI');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Dominica' ,'DMA');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Denmark' ,'DNK');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Dominican Republica' ,'DOM');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Algeria' ,'DZA');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Ecuador' ,'ECU');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Egypt' ,'EGY');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Eritrea' ,'ERI');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Spain' ,'ESP');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Estonia' ,'EST');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Ethiopia' ,'ETH');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Finland' ,'FIN');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Fiji' ,'FJI');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('France' ,'FRA');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Faroe Islands' ,'FRO');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Gabon' ,'GAB');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('United Kingdom of Great Britain and Northern Ireland' ,'GBR');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Georgia' ,'GEO');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Ghana' ,'GHA');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Guinea' ,'GIN');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Gambia' ,'GMB');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Greece' ,'GRC');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Greenland' ,'GRL');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Guatemala' ,'GTM');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Guam' ,'GUM');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Guyana' ,'GUY');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Hong Kong' ,'HKG');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Honduras' ,'HND');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Croatia' ,'HRV');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Haiti' ,'HTI');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Hungary' ,'HUN');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Indonesia' ,'IDN');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('India' ,'IND');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Ireland' ,'IRL');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Islamic Republic of Iran' ,'IRN');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Iraq' ,'IRQ');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Iceland' ,'ISL');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Israel' ,'ISR');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Italy' ,'ITA');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Jamaica' ,'JAM');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Jordan' ,'JOR');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Japan' ,'JPN');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Kazakhstan' ,'KAZ');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Kenya' ,'KEN');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Kyrgyzstan' ,'KGZ');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Cambodia' ,'KHM');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Republic of Korea' ,'KOR');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Kuwait' ,'KWT');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Lao Peoples Democratic Republic' ,'LAO');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Lebanon' ,'LBN');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Liberia' ,'LBR');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Libya' ,'LBY');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Liechtenstein' ,'LIE');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Sri Lanka' ,'LKA');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Lesotho' ,'LSO');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Lithuania' ,'LTU');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Luxembourg' ,'LUX');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Latvia' ,'LVA');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Macao' ,'MAC');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Morocco' ,'MAR');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Monaco' ,'MCO');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Moldova' ,'MDA');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Madagascar' ,'MDG');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Mexico' ,'MEX');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Mali' ,'MLI');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Malta' ,'MLT');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Maynmar' ,'MMR');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Mongolia' ,'MNG');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Mozambique' ,'MOZ');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Mauritania' ,'MRT');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Mauritius' ,'MUS');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Malawi' ,'MWI');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Malaysia' ,'MYS');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Namibia' ,'NAM');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Niger' ,'NER');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Nigeria' ,'NGA');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Nicaragua' ,'NIC');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Netherlands' ,'NLD');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Norway' ,'NOR');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Nepal' ,'NPL');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('New Zealand' ,'NZL');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Oman' ,'OMN');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Pakistan' ,'PAK');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Panama' ,'PAN');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Peru' ,'PER');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Philippines' ,'PHL');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Papua New Guinea' ,'PNG');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Poland' ,'POL');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Puerto Rico' ,'PRI');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Portugal' ,'PRT');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Paraguay' ,'PRY');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('State of Palestina' ,'PSE');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Qatar' ,'QAT');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Republic of Kosovo' ,'RKS');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Romania' ,'ROU');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Russian Federation' ,'RUS');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Rwanda' ,'RWA');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Saudi Arabia' ,'SAU');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Sudan' ,'SDN');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Senegal' ,'SEN');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Singapore' ,'SGP');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Solomon Islands' ,'SLB');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Sierra Leone' ,'SLE');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('El Salvador' ,'SLV');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('San Marino' ,'SMR');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Somalia' ,'SOM');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Serbia' ,'SRB');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('South Sudan' ,'SSD');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Suriname' ,'SUR');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Slovakia' ,'SVK');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Slovenia' ,'SVN');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Sweden' ,'SWE');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Eswatini' ,'SWZ');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Seychelles' ,'SYC');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Syrian Arab Republic' ,'SYR');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Chad' ,'TCD');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Togo' ,'TGO');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Thailand' ,'THA');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Tajikistan' ,'TJK');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Timor-Leste' ,'TLS');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Trinidad and Tobago' ,'TTO');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Tunisia' ,'TUN');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Turkey' ,'TUR');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Taiwan' ,'TWN');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Tanzania' ,'TZA');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Uganda' ,'UGA');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Ukraine' ,'UKR');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Uruguay' ,'URY');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('United States of America' ,'USA');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Uzbekistan' ,'UZB');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Venezuela' ,'VEN');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Virgin Islands (U.S.)' ,'VIR');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Viet Nam' ,'VNM');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Vanuatu' ,'VUT');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Yemen' ,'YEM');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('South Africa' ,'ZAF');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Zambia' ,'ZMB');
INSERT INTO CountriesNames (Name, CountryCodeId) VALUES('Zimbabwe' ,'ZWE') 